data: data/stories/STORIES_BPE
save_checkpoint_steps: 2000
keep_checkpoint: 10
seed: 123
warmup_steps: 8000
train_steps: 100000
valid_steps: 800
report_every: 100

decoder_type: transformer
encoder_type: transformer
word_vec_size: 768
rnn_size: 768
enc_layers: 6
dec_layers: 12
transformer_ff: 3072
enc_heads: 8
dec_heads: 12
use_GPT_version_ctxattn: 'true'

accum_count: 14
optim: adam
adam_beta1: 0.9
adam_beta2: 0.98
decay_method: invsq
learning_rate: 0.0005
warmup_init_factor: 5000
max_grad_norm: 0.0
disc_ft: 1.2
dec_lr_factor: 3

batch_size: 2048
valid_batch_size: 4
batch_type: tokens
normalization: tokens
dropout: 0.25
attn_dropout: 0.2
label_smoothing: 0.1

max_generator_batches: 0
force_bs1: 'true'

param_init: 0.0
param_init_glorot: 'true'
position_encoding: 'true'
position_encoding_learned: 'true'
position_encoding_ctxsize: 1024
share_decoder_embeddings: 'true'
share_embeddings: 'true' # This is not quite the same, but probably should only have positive effect?
share_position_embeddings: 'true'

world_size: 4
gpu_ranks:
- 0
- 1
- 2
- 3
tensorboard: 'true'
